name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Create directories
      run: |
        mkdir -p bin
        mkdir -p results
    
    - name: Compile code
      run: javac -Xlint:unchecked -cp "lib/cloudsim-3.0.3.jar" -d bin src/org/cloudbus/cloudsim/*.java
    
    - name: Run simulation
      run: java -cp "bin:lib/cloudsim-3.0.3.jar:lib/cloudsim-examples-3.0.3.jar" org.cloudbus.cloudsim.Main
    
    - name: Create docs directory for GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        mkdir -p docs
        cp -r results/* docs/
        # Create a simple Jekyll configuration file
        echo "theme: jekyll-theme-cayman" > docs/_config.yml
    
    - name: Commit and push results
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add results/ docs/
        git commit -m "Update simulation results [skip ci]" || echo "No changes to commit"
        git push origin HEAD:${GITHUB_REF#refs/heads/} || echo "Nothing to push"