name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Create directories
      run: |
        mkdir -p bin
        mkdir -p results
    
    - name: Compile code
      run: javac -cp "lib/cloudsim-3.0.3.jar" -d bin src/org/cloudbus/cloudsim/*.java
    
    - name: Run simulation
      run: java -cp "bin:lib/cloudsim-3.0.3.jar:lib/cloudsim-examples-3.0.3.jar" org.cloudbus.cloudsim.Main
    
    - name: Create docs directory for GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        mkdir -p docs
        cp -r results/* docs/
        touch docs/.nojekyll
        # Simplified _config.yml to avoid Jekyll processing
        echo "theme: none" > docs/_config.yml
        # Basic HTML file that doesn't require any processing
        echo "<html><head><title>CloudSim Simulation Results</title><style>body{font-family:Arial,sans-serif;margin:40px}</style></head><body><h1>CloudSim Simulation Results</h1><p>View the <a href='simulation_results.csv'>simulation results</a>.</p></body></html>" > docs/index.html
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
        clean: true