name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    # Step 2: Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # OpenJDK distribution
    
    # Step 3: Create required directories
    - name: Create directories
      run: |
        mkdir -p bin
        mkdir -p results
    
    # Step 4: Compile the code
    - name: Compile code
      run: javac -Xlint:unchecked -cp "lib/cloudsim-3.0.3.jar" -d bin src/org/cloudbus/cloudsim/*.java
    
    # Step 5: Run the simulation
    - name: Run simulation
      run: java -cp "bin:lib/cloudsim-3.0.3.jar:lib/cloudsim-examples-3.0.3.jar" org.cloudbus.cloudsim.Main
    
    # Step 6: Ensure results exist
    - name: Ensure results exist
      run: |
        if [ ! -f "results/simulation_results.csv" ]; then
          echo "No simulation results found, creating placeholder"
          mkdir -p results
          echo "timestamp,vm_count,host_utilization,status" > results/simulation_results.csv
          echo "$(date -u +"%Y-%m-%d %H:%M:%S"),0,0.0,placeholder" >> results/simulation_results.csv
        fi
    
    # Step 7: Prepare GitHub Pages (only on main/master)
    - name: Prepare GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # Create docs directory
        mkdir -p docs
        
        # Copy results files
        cp -r results/* docs/ || echo "No results to copy"
        
        # Create .nojekyll file to disable Jekyll processing completely
        touch docs/.nojekyll
        
        # Create simple index.html
        echo "<html>
          <head>
            <title>CloudSim Simulation Results</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6 }
              table { border-collapse: collapse; width: 100% }
              th, td { border: 1px solid #ddd; padding: 8px; text-align: left }
              th { background-color: #f2f2f2 }
            </style>
          </head>
          <body>
            <h1>CloudSim Simulation Results</h1>
            <p>Last updated: $(date -u)</p>
            <p>View the <a href='simulation_results.csv'>simulation results</a>.</p>
          </body>
        </html>" > docs/index.html
        
        # List contents for debugging
        echo "Contents of docs directory:"
        ls -la docs/
    
    # Step 8: Deploy to GitHub Pages - ONLY using the JamesIves action
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
        clean: true